/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ZigZagZogAbi } from "./ZigZagZogAbi";
export * as factories from "./factories";
export { ZigZagZogAbi__factory } from "./factories/ZigZagZogAbi__factory";
